facility_life_expectancy_data = [
    {"key": 1, "label": "Heating - Cooling Plant", "life_expectancy": 60},
    {"key": 2, "label": "Antenna support building", "life_expectancy": 30},
    {"key": 3, "label": "Communication Facility", "life_expectancy": 60},
    {"key": 4, "label": "Power generation Facility", "life_expectancy": 60},
    {"key": 5, "label": "Ground Terminal T1", "life_expectancy": 30},
    {"key": 6, "label": "Ops Facility T1", "life_expectancy": 50},
    {"key": 7, "label": "Data Center", "life_expectancy": 40},
    {"key": 8, "label": "Receiver Station", "life_expectancy": 30},
    {"key": 9, "label": "Ground monitoring Station", "life_expectancy": 30},
    {"key": 10, "label": "Pump Station", "life_expectancy": 40},
    {"key": 11, "label": "Admin Office", "life_expectancy": 40},
    {"key": 12, "label": "Equipment Pad", "life_expectancy": 20},
    {"key": 13, "label": "Fuel Building", "life_expectancy": 50},
    {"key": 14, "label": "Dorm Facility", "life_expectancy": 50},
    {"key": 15, "label": "Central Utility Plant", "life_expectancy": 50},
    {"key": 16, "label": "Truck fill stand", "life_expectancy": 30},
    {"key": 17, "label": "Entry control point", "life_expectancy": 30},
    {"key": 18, "label": "Utility corridor", "life_expectancy": 60},
    {"key": 19, "label": "Maintenance Shop", "life_expectancy": 40},
    {"key": 20, "label": "Fuel Farm", "life_expectancy": 40},
    {"key": 21, "label": "Radome Facility", "life_expectancy": 30},
    {"key": 22, "label": "Water Treatment Facility", "life_expectancy": 30},
    {"key": 23, "label": "Standby Generator", "life_expectancy": 30},
    {"key": 24, "label": "UPS Building", "life_expectancy": 50},
    {"key": 25, "label": "Switching Station", "life_expectancy": 30},
    {"key": 26, "label": "Substation", "life_expectancy": 30},
    {"key": 27, "label": "Fuel intake Facility", "life_expectancy": 30},
    {"key": 28, "label": "Storage Facility", "life_expectancy": 60},
]
